/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/_admin/dashboard/index'
import { Route as AdminConnectorsDefinitionsIndexRouteImport } from './routes/_admin/connectors-definitions/index'
import { Route as AuthCallbackMicrosoftRouteImport } from './routes/auth/callback/microsoft'
import { Route as AuthCallbackGoogleRouteImport } from './routes/auth/callback/google'
import { Route as AdminSettingsConnectorsIndexRouteImport } from './routes/_admin/settings/connectors/index'
import { Route as AdminDigitalAssetsOrdersIndexRouteImport } from './routes/_admin/digital-assets/orders/index'
import { Route as AdminDigitalAssetsOrdersOpenIndexRouteImport } from './routes/_admin/digital-assets/orders-open/index'
import { Route as AdminDigitalAssetsOrdersHistoryIndexRouteImport } from './routes/_admin/digital-assets/orders-history/index'
import { Route as AdminDigitalAssetsAssetsIndexRouteImport } from './routes/_admin/digital-assets/assets/index'
import { Route as AdminDigitalAssetsOrdersOrderIdRouteImport } from './routes/_admin/digital-assets/orders/$orderId'
import { Route as AdminSettingsConnectorsCallbackBybitRouteImport } from './routes/_admin/settings/connectors/callback/bybit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectorsDefinitionsIndexRoute =
  AdminConnectorsDefinitionsIndexRouteImport.update({
    id: '/connectors-definitions/',
    path: '/connectors-definitions/',
    getParentRoute: () => AdminRoute,
  } as any)
const AuthCallbackMicrosoftRoute = AuthCallbackMicrosoftRouteImport.update({
  id: '/auth/callback/microsoft',
  path: '/auth/callback/microsoft',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackGoogleRoute = AuthCallbackGoogleRouteImport.update({
  id: '/auth/callback/google',
  path: '/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsConnectorsIndexRoute =
  AdminSettingsConnectorsIndexRouteImport.update({
    id: '/settings/connectors/',
    path: '/settings/connectors/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDigitalAssetsOrdersIndexRoute =
  AdminDigitalAssetsOrdersIndexRouteImport.update({
    id: '/digital-assets/orders/',
    path: '/digital-assets/orders/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDigitalAssetsOrdersOpenIndexRoute =
  AdminDigitalAssetsOrdersOpenIndexRouteImport.update({
    id: '/digital-assets/orders-open/',
    path: '/digital-assets/orders-open/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDigitalAssetsOrdersHistoryIndexRoute =
  AdminDigitalAssetsOrdersHistoryIndexRouteImport.update({
    id: '/digital-assets/orders-history/',
    path: '/digital-assets/orders-history/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDigitalAssetsAssetsIndexRoute =
  AdminDigitalAssetsAssetsIndexRouteImport.update({
    id: '/digital-assets/assets/',
    path: '/digital-assets/assets/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDigitalAssetsOrdersOrderIdRoute =
  AdminDigitalAssetsOrdersOrderIdRouteImport.update({
    id: '/digital-assets/orders/$orderId',
    path: '/digital-assets/orders/$orderId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsConnectorsCallbackBybitRoute =
  AdminSettingsConnectorsCallbackBybitRouteImport.update({
    id: '/settings/connectors/callback/bybit',
    path: '/settings/connectors/callback/bybit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
  '/auth/callback/microsoft': typeof AuthCallbackMicrosoftRoute
  '/connectors-definitions': typeof AdminConnectorsDefinitionsIndexRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/digital-assets/orders/$orderId': typeof AdminDigitalAssetsOrdersOrderIdRoute
  '/digital-assets/assets': typeof AdminDigitalAssetsAssetsIndexRoute
  '/digital-assets/orders-history': typeof AdminDigitalAssetsOrdersHistoryIndexRoute
  '/digital-assets/orders-open': typeof AdminDigitalAssetsOrdersOpenIndexRoute
  '/digital-assets/orders': typeof AdminDigitalAssetsOrdersIndexRoute
  '/settings/connectors': typeof AdminSettingsConnectorsIndexRoute
  '/settings/connectors/callback/bybit': typeof AdminSettingsConnectorsCallbackBybitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
  '/auth/callback/microsoft': typeof AuthCallbackMicrosoftRoute
  '/connectors-definitions': typeof AdminConnectorsDefinitionsIndexRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/digital-assets/orders/$orderId': typeof AdminDigitalAssetsOrdersOrderIdRoute
  '/digital-assets/assets': typeof AdminDigitalAssetsAssetsIndexRoute
  '/digital-assets/orders-history': typeof AdminDigitalAssetsOrdersHistoryIndexRoute
  '/digital-assets/orders-open': typeof AdminDigitalAssetsOrdersOpenIndexRoute
  '/digital-assets/orders': typeof AdminDigitalAssetsOrdersIndexRoute
  '/settings/connectors': typeof AdminSettingsConnectorsIndexRoute
  '/settings/connectors/callback/bybit': typeof AdminSettingsConnectorsCallbackBybitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
  '/auth/callback/microsoft': typeof AuthCallbackMicrosoftRoute
  '/_admin/connectors-definitions/': typeof AdminConnectorsDefinitionsIndexRoute
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_admin/digital-assets/orders/$orderId': typeof AdminDigitalAssetsOrdersOrderIdRoute
  '/_admin/digital-assets/assets/': typeof AdminDigitalAssetsAssetsIndexRoute
  '/_admin/digital-assets/orders-history/': typeof AdminDigitalAssetsOrdersHistoryIndexRoute
  '/_admin/digital-assets/orders-open/': typeof AdminDigitalAssetsOrdersOpenIndexRoute
  '/_admin/digital-assets/orders/': typeof AdminDigitalAssetsOrdersIndexRoute
  '/_admin/settings/connectors/': typeof AdminSettingsConnectorsIndexRoute
  '/_admin/settings/connectors/callback/bybit': typeof AdminSettingsConnectorsCallbackBybitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/register'
    | '/reset-password'
    | '/auth/callback/google'
    | '/auth/callback/microsoft'
    | '/connectors-definitions'
    | '/dashboard'
    | '/digital-assets/orders/$orderId'
    | '/digital-assets/assets'
    | '/digital-assets/orders-history'
    | '/digital-assets/orders-open'
    | '/digital-assets/orders'
    | '/settings/connectors'
    | '/settings/connectors/callback/bybit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/register'
    | '/reset-password'
    | '/auth/callback/google'
    | '/auth/callback/microsoft'
    | '/connectors-definitions'
    | '/dashboard'
    | '/digital-assets/orders/$orderId'
    | '/digital-assets/assets'
    | '/digital-assets/orders-history'
    | '/digital-assets/orders-open'
    | '/digital-assets/orders'
    | '/settings/connectors'
    | '/settings/connectors/callback/bybit'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/register'
    | '/reset-password'
    | '/auth/callback/google'
    | '/auth/callback/microsoft'
    | '/_admin/connectors-definitions/'
    | '/_admin/dashboard/'
    | '/_admin/digital-assets/orders/$orderId'
    | '/_admin/digital-assets/assets/'
    | '/_admin/digital-assets/orders-history/'
    | '/_admin/digital-assets/orders-open/'
    | '/_admin/digital-assets/orders/'
    | '/_admin/settings/connectors/'
    | '/_admin/settings/connectors/callback/bybit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackGoogleRoute: typeof AuthCallbackGoogleRoute
  AuthCallbackMicrosoftRoute: typeof AuthCallbackMicrosoftRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/connectors-definitions/': {
      id: '/_admin/connectors-definitions/'
      path: '/connectors-definitions'
      fullPath: '/connectors-definitions'
      preLoaderRoute: typeof AdminConnectorsDefinitionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/callback/microsoft': {
      id: '/auth/callback/microsoft'
      path: '/auth/callback/microsoft'
      fullPath: '/auth/callback/microsoft'
      preLoaderRoute: typeof AuthCallbackMicrosoftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/google': {
      id: '/auth/callback/google'
      path: '/auth/callback/google'
      fullPath: '/auth/callback/google'
      preLoaderRoute: typeof AuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/settings/connectors/': {
      id: '/_admin/settings/connectors/'
      path: '/settings/connectors'
      fullPath: '/settings/connectors'
      preLoaderRoute: typeof AdminSettingsConnectorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/digital-assets/orders/': {
      id: '/_admin/digital-assets/orders/'
      path: '/digital-assets/orders'
      fullPath: '/digital-assets/orders'
      preLoaderRoute: typeof AdminDigitalAssetsOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/digital-assets/orders-open/': {
      id: '/_admin/digital-assets/orders-open/'
      path: '/digital-assets/orders-open'
      fullPath: '/digital-assets/orders-open'
      preLoaderRoute: typeof AdminDigitalAssetsOrdersOpenIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/digital-assets/orders-history/': {
      id: '/_admin/digital-assets/orders-history/'
      path: '/digital-assets/orders-history'
      fullPath: '/digital-assets/orders-history'
      preLoaderRoute: typeof AdminDigitalAssetsOrdersHistoryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/digital-assets/assets/': {
      id: '/_admin/digital-assets/assets/'
      path: '/digital-assets/assets'
      fullPath: '/digital-assets/assets'
      preLoaderRoute: typeof AdminDigitalAssetsAssetsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/digital-assets/orders/$orderId': {
      id: '/_admin/digital-assets/orders/$orderId'
      path: '/digital-assets/orders/$orderId'
      fullPath: '/digital-assets/orders/$orderId'
      preLoaderRoute: typeof AdminDigitalAssetsOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/connectors/callback/bybit': {
      id: '/_admin/settings/connectors/callback/bybit'
      path: '/settings/connectors/callback/bybit'
      fullPath: '/settings/connectors/callback/bybit'
      preLoaderRoute: typeof AdminSettingsConnectorsCallbackBybitRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConnectorsDefinitionsIndexRoute: typeof AdminConnectorsDefinitionsIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDigitalAssetsOrdersOrderIdRoute: typeof AdminDigitalAssetsOrdersOrderIdRoute
  AdminDigitalAssetsAssetsIndexRoute: typeof AdminDigitalAssetsAssetsIndexRoute
  AdminDigitalAssetsOrdersHistoryIndexRoute: typeof AdminDigitalAssetsOrdersHistoryIndexRoute
  AdminDigitalAssetsOrdersOpenIndexRoute: typeof AdminDigitalAssetsOrdersOpenIndexRoute
  AdminDigitalAssetsOrdersIndexRoute: typeof AdminDigitalAssetsOrdersIndexRoute
  AdminSettingsConnectorsIndexRoute: typeof AdminSettingsConnectorsIndexRoute
  AdminSettingsConnectorsCallbackBybitRoute: typeof AdminSettingsConnectorsCallbackBybitRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConnectorsDefinitionsIndexRoute: AdminConnectorsDefinitionsIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDigitalAssetsOrdersOrderIdRoute: AdminDigitalAssetsOrdersOrderIdRoute,
  AdminDigitalAssetsAssetsIndexRoute: AdminDigitalAssetsAssetsIndexRoute,
  AdminDigitalAssetsOrdersHistoryIndexRoute:
    AdminDigitalAssetsOrdersHistoryIndexRoute,
  AdminDigitalAssetsOrdersOpenIndexRoute:
    AdminDigitalAssetsOrdersOpenIndexRoute,
  AdminDigitalAssetsOrdersIndexRoute: AdminDigitalAssetsOrdersIndexRoute,
  AdminSettingsConnectorsIndexRoute: AdminSettingsConnectorsIndexRoute,
  AdminSettingsConnectorsCallbackBybitRoute:
    AdminSettingsConnectorsCallbackBybitRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackGoogleRoute: AuthCallbackGoogleRoute,
  AuthCallbackMicrosoftRoute: AuthCallbackMicrosoftRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
